import type { Metadata } from "next";
import Header from "@/app/layout_components/header/header";
import "./globals.css";
import { Poppins, Updock } from 'next/font/google';
import Footer from "./layout_components/footer/footer";
import CartBadgeUpdater from "./layout_components/cart-badge-updater";
import { Toaster } from "react-hot-toast";
import SessionWrapper from "@/components/SessionWrapper";


const headingFont = Updock({
  weight: ['400'],
  subsets: ['latin'],
  variable: '--head',
});

const bodyFont = Poppins({
  weight: ['500'],
  subsets: ['latin'],
  variable: '--body',
});

export const metadata: Metadata = {
  title: {
    default: "Handcrafted Haven",
    template: '%s | Handcrafted Haven'
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <SessionWrapper>
          <Header /> 
          {children}
        </SessionWrapper>
      </body>
    </html>
  );
}